distributed:
  dashboard:
    link:  "{scheme}://{host}:{port}/status"
  worker:
    profile:
      enabled: true
    memory:
      terminate: false
    multiprocessing-method: spawn
    daemon: false
    
  comm:
    retry:
      count: 100
    timeouts:
      connect: 1000
      tcp: 1000
  deploy:
    lost-worker-timeout: 100
  # nanny:
  #   environ:
  #     MALLOC_TRIM_THRESHOLD_: 0
  # scheduler:
  scheduler:
    events-log-length: 0
    worker-saturation: 1.1
  # admin:
  #   log-length: 0
  # diagnostics:
  #   computations:
  #     max-history: 0

optimization: {}
  # fuse:
  #   ave-width: 10000
  #   delayed: true
  #   active: true

adaptive:
  wait-count: 20

jobqueue:
  lpccondor:
    name: dask-worker
    # Dask worker options
    cores: 1                     # Total number of cores per job
    memory: 2.5GB                # Total amount of memory per job
    processes: False                 # Number of Python processes per jo
    threads: 1

    interface: null             # Network interface to use like eth0 or ib0
    death-timeout: 120           # Number of seconds to wait if a worker can not find a scheduler
    local-directory: /srv       # Location of fast local storage like /scratch or $TMPDIR
    shared-temp-directory: null
    extra: null

    worker-extra-args:
      - "--worker-port 10000:10300"
      - "--nanny-port 10301:10600"
      - "--no-dashboard"

    # HTCondor Resource Manager options
    disk: 4GB                  # Total amount of disk per job
    job-extra: {}               # Extra submit attributes
    log-directory: logs
    env-extra: null
    job-script-prologue:
      - 'tar xzf environment.tar.gz'
      - 'tar xzf analyzer.tar.gz'
      - '[[ -f extra_files.tar.gz ]] &&  tar xzf extra_files.tar.gz'
      - 'source setup.sh bashrc'
      - echo "Virtual ENV IS" $VIRTUAL_ENV
      - ls -alhtr
      - ls -alhtr .application_data
      - export X509_USER_PROXY=$(realpath $(find . -iname 'x509*'))
      - echo 'X509 Is'
      - echo $X509_USER_PROXY

    job-extra: null             # Extra submit attributes
    job-extra-directives: {}
    job-directives-skip: []
    submit-command-extra: []    # Extra condor_submit arguments
    cancel-command-extra: []    # Extra condor_rm arguments
    log-directory: null
    shebang: "#!/usr/bin/env condor_submit" # doesn't matter
    
    # Scheduler options
    scheduler-options: {}
