---
version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  just_name:
    format: "%(name)s - %(message)s"

handlers:
  debug_console:
    class: rich.logging.RichHandler
    level: DEBUG
    formatter: just_name

  error_console:
    class: rich.logging.RichHandler
    level: ERROR
    formatter: just_name

  info_console:
    class: rich.logging.RichHandler
    level: INFO
    formatter: just_name

  warn_console:
    class: rich.logging.RichHandler
    level: WARN
    formatter: just_name

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logs/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    formatter: simple
    encoding: utf8

loggers:
  analyzer:
    level: INFO
    handlers: [file_handler, debug_console]
  distributed:
    level: INFO
    handlers: [file_handler, warn_console]
  distributed.worker:
    level: WARNING
    handlers: [file_handler, warn_console]
  distributed.client:
    level: WARNING
    handlers: [file_handler, warn_console]
  distributed.bokeh:
    level: ERROR
    handlers: [file_handler, warn_console]
  lpcjobqueue.cluster:
    level: INFO 
    handlers: [file_handler, warn_console]

root:
  level: INFO
  handlers: [warn_console, file_handler]
