---
version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  just_name:
    format: "%(name)s\n%(message)s"

handlers:
  info_console:
    class: rich.logging.RichHandler
    level: INFO
    formatter: just_name
  warn_console:
    class: rich.logging.RichHandler
    level: WARN
    formatter: just_name

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logs/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    formatter: simple
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  analyzer:
    level: DEBUG
    handlers: [debug_file_handler, info_console]
    propagate: false
  distributed.core:
    level: DEBUG
    handlers: [debug_file_handler, warn_console]
    propagate: false
  distributed.client:
    level: DEBUG
    handlers: [debug_file_handler, warn_console]
    propagate: false
  distributed.scheduler:
    level: DEBUG
    handlers: [debug_file_handler, warn_console]
    propagate: false
  dask:
    level: DEBUG 
    handlers: [warn_console, debug_file_handler]
    propagate: false

root:
  level: WARN
  handlers: [warn_console]
