---
version: 1

disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  just_name:
    format: "%(name)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple


loggers:
  analyzer:
    level: INFO
    handlers: [console]
