* Introduction
Coffea is a columnar analysis framework, has a similar interface to common python packages like numpy or pandas.
This repository is an implementation of the single stop analysis written in Coffea. 

* Getting started
Begin by cloning and entering the repository.
#+begin_src bash
git clone git@github.com:UMN-CMS/SingleStopCoffea.git
cd SingleStopCoffea
#+end_src

Getting things setup should be as simple as running
#+begin_src bash
source setup.sh
#+end_src
This will automatically source the correct LCG environment and install the dependencies.

* Running the Program
The entrypoint for the program is the command
#+begin_src bash
python3 -m analyzer
#+end_src



* Extending the Analysis


* Scaling Out


* Using Notebooks
Coffea works very nicely when used with jupyter notebooks. Chances are you want to run the notebook on a remote node, but view it in your local browser.
This is accomplished by forwarding a port from your local machine to the remote machine using the below ssh command
#+begin_src bash
ssh -N -L 5000:localhost:8999 username@remotehost
#+end_src
On the remote host, start the notebook by running from within the python environment,
#+begin_src bash
jupyter notebook --no-browser --port 8999
#+end_src
You can pick any port, for the remote machine, and you may need to if someone else is using that port.

The notebook [[file:notebooks/example.ipynb]] shows an example of doing basic analysis within a notebook.



