# The name of analysis to be run
name: SingleStop

# Samples and in which regions they should be processed
samples:
  signal_312_2000_1900: [Signal312,Control]
  Data2018: [Control, Signal312, Signal313]
  QCDInclusive2018: [Signal312,Control, Signal313]
  signal_312_1500_1400: [Signal312, Control]
  signal_312_1200_400: [Signal312, Control]
  signal_312_1200_600: [Signal312, Control]
  signal_312_1200_1100: [Signal312, Control]
  signal_312_1300_1200: [Signal312, Control]
  signal_312_1400_400: [Signal312, Control]
  signal_312_1400_1300: [Signal312, Control]
  signal_312_1500_400: [Signal312, Control]
  signal_312_1500_600: [Signal312, Control]
  signal_312_1500_900: [Signal312, Control]
  signal_312_1500_1400: [Signal312, Control]
  signal_312_2000_400: [Signal312, Control]
  signal_312_1300_400: [Signal312, Control]
  signal_312_1300_600: [Signal312, Control]
  signal_312_2000_900: [Signal312, Control]
  signal_312_2000_1900: [Signal312, Control]
  signal_312_1000_700: [Signal312, Control]
  signal_312_1000_800: [Signal312, Control]
  signal_312_1200_700: [Signal312, Control]
  signal_312_1200_800: [Signal312, Control]
  signal_312_1500_100: [Signal312, Control]
  signal_312_1500_1000: [Signal312, Control]
  signal_312_1500_1200: [Signal312, Control]
  signal_312_1500_1300: [Signal312, Control]
  signal_312_1500_1350: [Signal312, Control]
  signal_312_1500_1450: [Signal312, Control]
  signal_312_2000_1200: [Signal312, Control]
  signal_312_2000_1600: [Signal312, Control]
  signal_312_2000_1700: [Signal312, Control]
  signal_312_1000_400: [Signal312, Control]
  signal_312_1000_600: [Signal312, Control]
  signal_312_1000_900: [Signal312, Control]

# Samples and in which regions they should be processed
execution_config:
  cluster_type: lpccondor
  max_workers: 20
  worker_memory: 2GB
  worker_timeout: 7200
  chunk_size: 100000

file_config:
  location_priority_regex: [".*FNAL.*", ".*US.*", ".*(DE|IT|CH|FR).*", ".*(T0|T1|T2).*","eos"]
  use_replicas: True
  skimming:
    output: "root://blabla/SingleStop/"
    use_skims_path: "root://blabla/SingleStop/"

# You can use yaml anchors to reduce the amount of duplication in the configuration file
common_items:
    common_signal_histograms: &common_signal
      - name: njets
      - name: goodjet_ht
      - name: jet_kinematics
      - name: jet_combo_kinematics
      - name: b_quark_kinematics
        config:
          - working_point: L
          - working_point: M
          - working_point: T

    common_objects: &common_objects
      - name: core_objects

    common_preselection: &common_preselection 
      - name: golden_lumi_filter
        sample_spec:
          sample_type: Data

    common_weights: &common_weights
      - name: L1_prefiring_sf
        sample_spec:
          eras: ["2016", "2017", "2018"]
          sample_type: MC
        config:
          variations: All

      - name: sign_gen_weight
        sample_spec:
          sample_type: MC

      - name: pileup_sf
        sample_spec:
          sample_type: MC


# A region has a name, followed by description of what modules should be run
# for each stage of the analysis: preselection, object_creation, selection, categorization, and histogram production for the given region.
# Additionally, a module may also have a `sample_spec` option, which limits which samples it applies to, ie only make gen-level hists for MC.
# Weighting information is defined in the weights nodes, described below.
regions:
 # - name: Signal313
 #   forbid_data: true
 #   objects: *common_objects
 #   preselection:
 #     - name: selection_hlt
 #   selection:
 #     - name: general_selection
 #     - name: 313_selection
 #   categories:
 #     - njets_category:
 #   histograms: *common_signal
 #   weights:
 #     - <<: *common_weights
 #     - name: btag_scale_factors
 #       config:
 #           working_points: [T]
  - name: Signal312
    forbid_data: false
    objects: *common_objects
    preselection:
      - <<: *common_preselection
      - name: signal_hlt
    selection: 
      - name: general_selection
      - name: partial_signal312_selection
    histograms: *common_signal
    weights: *common_weights


  - name: Control
    objects: *common_objects
    preselection:
      - <<: *common_preselection
      - name: signal_hlt
    selection: 
      - name: general_selection
      - name: partial_cr_selection
    histograms: *common_signal
    weights: *common_weights

